	pip install alembic
	pip install amqp
	pip install astroid
	pip install Babel
	pip install billiard
	pip install bunch
	pip install celery
	pip install click
	pip install colorama
	pip install dominate
	pip install Flask
	pip install Flask-Admin
	pip install Flask-Bootstrap
	pip install Flask-Login
	pip install Flask-MAB
	pip install Flask-Markdown
	pip install Flask-Migrate
	pip install Flask-Script
	pip install Flask-Session
	pip install Flask-SQLAlchemy
	pip install Flask-WTF
	pip install flower
	pip install gunicorn
	pip install isort
	pip install itsdangerous
	pip install Jinja2
	pip install kombu
	pip install lazy-object-proxy
	pip install Mako
	pip install Markdown
	pip install MarkupSafe
	pip install mccabe
	pip install pandas
	pip install psycopg2
	pip install pylint
	pip install python-dateutil
	pip install python-editor
	pip install pytz
	pip install redis
	pip install rpy2
	pip install six
	pip install SQLAlchemy
	pip install tornado
	pip install typed-ast
	pip install tzlocal
	pip install vine
	pip install visitor
	pip install Werkzeug
	pip install wrapt
	pip install WTForms
