	pip3 install alembic
	pip3 install amqp
	pip3 install astroid
	pip3 install Babel
	pip3 install billiard
	pip3 install bunch
	pip3 install celery
	pip3 install click
	pip3 install colorama
	pip3 install dominate
	pip3 install Flask
	pip3 install Flask-Admin
	pip3 install Flask-Bootstrap
	pip3 install Flask-Login
	pip3 install Flask-MAB
	pip3 install Flask-Markdown
	pip3 install Flask-Migrate
	pip3 install Flask-Script
	pip3 install Flask-Session
	pip3 install Flask-SQLAlchemy
	pip3 install Flask-WTF
	pip3 install flower
	pip3 install gunicorn
	pip3 install isort
	pip3 install itsdangerous
	pip3 install Jinja2
	pip3 install kombu
	pip3 install lazy-object-proxy
	pip3 install Mako
	pip3 install Markdown
	pip3 install MarkupSafe
	pip3 install mccabe
	pip3 install pandas
	pip3 install psycopg2
	pip3 install pylint
	pip3 install python-dateutil
	pip3 install python-editor
	pip3 install pytz
	pip3 install redis
	pip3 install rpy2
	pip3 install six
	pip3 install SQLAlchemy
	pip3 install tornado
	pip3 install typed-ast
	pip3 install tzlocal
	pip3 install vine
	pip3 install visitor
	pip3 install Werkzeug
	pip3 install wrapt
	pip3 install WTForms
