"""empty message

Revision ID: 02da16c2c4ed
Revises: 546a8ba02f44
Create Date: 2018-11-17 21:58:01.131946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02da16c2c4ed'
down_revision = '546a8ba02f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covariance_matrix',
    sa.Column('diff_row', sa.String(length=4), nullable=False),
    sa.Column('diff_col', sa.String(length=4), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('diff_row','diff_col')
    )
    op.add_column('phrase', sa.Column('statut', sa.String(length=14), nullable=True))
    op.drop_column('phrase', 'a_revoir')
    op.add_column('stats_difficultes', sa.Column('irt_mean', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_difficultes', 'irt_mean')
    op.add_column('phrase', sa.Column('a_revoir', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('phrase', 'statut')
    op.drop_table('covariance_matrix')
    # ### end Alembic commands ###
