"""empty message

Revision ID: 546a8ba02f44
Revises: da1800cd2921
Create Date: 2018-11-02 22:19:27.405261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546a8ba02f44'
down_revision = 'da1800cd2921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_phrases', sa.Column('irt_a1', sa.Float(), nullable=True))
    op.add_column('stats_phrases', sa.Column('irt_d', sa.Float(), nullable=True))
    op.add_column('stats_phrases', sa.Column('irt_g', sa.Float(), nullable=True))
    op.add_column('stats_phrases', sa.Column('irt_u', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_phrases', 'irt_u')
    op.drop_column('stats_phrases', 'irt_g')
    op.drop_column('stats_phrases', 'irt_d')
    op.drop_column('stats_phrases', 'irt_a1')
    # ### end Alembic commands ###
