"""empty message

Revision ID: da1800cd2921
Revises: 
Create Date: 2018-10-05 23:30:07.588931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1800cd2921'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_phrases', sa.Column('nb_reponses', sa.Integer(), nullable=True))
    op.drop_index('ix_utilisateur_username', table_name='utilisateur')
    op.create_index(op.f('ix_utilisateur_username'), 'utilisateur', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisateur_username'), table_name='utilisateur')
    op.create_index('ix_utilisateur_username', 'utilisateur', ['username'], unique=1)
    op.drop_column('stats_phrases', 'nb_reponses')
    # ### end Alembic commands ###
